#!/bin/bash -eu
set -o pipefail


function run_test() {
  local BASE_PATH="$(cd "$(dirname "$0")/.."; pwd)"
  local WORKSPACE="/tmp/jenkins-plugin-fixator-test"

  local BASE_COMMAND="$BASE_PATH/bin/jenkins-plugin-fixator"
  local RESULT_DIR="$WORKSPACE/result"
  local RESULT_STDOUT="$RESULT_DIR/$(basename "$0").stdout"
  local RESULT_STDERR="$RESULT_DIR/$(basename "$0").stderr"

  mkdir -p "$RESULT_DIR"
  echo > "$RESULT_STDOUT"
  echo > "$RESULT_STDERR"

  local JENKINS_PORT='3001'
  local ENDPOINT="http://localhost:$JENKINS_PORT"

  source "$BASE_PATH/test/helper.bash"


  ENDPOINT="$ENDPOINT" "$BASE_COMMAND" "await" \
    >> "$RESULT_STDOUT" 2>> "$RESULT_STDERR" \
    && ok "$LINENO" || ng "$LINENO"

	sleep "$EXPLICIT_WAIT_SEC"
}


run_test
